server:
  port: 8082

spring:
  application:
    name: turbine

eureka:  
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: false
    lease:
      duration: 5 


turbine:
 cluster-name-expression: new String("default") 
 app-config: google
 combine-host-port: true
 aggregator:      
   cluster-config: default