management:
  security:  
    enabled: false  
    
spring:
  application:
    name: eureka

server:
  port: 8761
  

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8761
  
